alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias la='ls -alhi --color=auto'
alias cc='claude --enable-auto-mode'
alias vim='nvim'
alias cat='bat --paging=never'
alias fvim='nvim $(fzf --preview="bat --color=always {}")'
alias fcode='code $(find . -type d -print | fzf)'
alias fcat='cat $(fzf)'
alias fcd='cd $(find . -type d -print | fzf)'
alias fpbcopy='/bin/cat $(fzf) | pbcopy'
alias fkill="ps -e | tail -n +2 | fzf | awk '{print \$1}' | xargs kill"
