# Path to your oh-my-zsh installation.
export ZSH=/home/leonardo/.oh-my-zsh

# Exporting Neo-Vim as editor
export EDITOR="nvim"
export VISUAL="nvim"
export TERM=xterm-256color

# ZSH Theme
ZSH_THEME="miloshadzic"

# Enable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="false"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=13

# Enable colors in ls.
DISABLE_LS_COLORS="false"

# Disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Enable command auto-correction.
ENABLE_CORRECTION="false"
DISABLE_CORRECTION="true"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

## Shell options

# Assume "cd" when a command is a directory
setopt autocd 

# Share the same history between all shells
setopt sharehistory 

# Disables auto-correction
unsetopt correct
unsetopt correct_all 


# Plugins

plugins=(
  git
  zsh-syntax-highlighting
  zsh-autosuggestions
  tmux
  tmuxinator
  colored-man-pages
  git-flow
)

source $ZSH/oh-my-zsh.sh
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
source ~/.zsh/prompt.sh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# User configuration
export LANG=en_US.UTF-8

# Aliases
alias vi='nvim'
alias vim='nvim'
alias song-dl='youtube-dl --extract-audio --audio-format mp3 -o "/MeuBolso/Songs/%(title)s.%(ext)s"' 
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
alias t='sh ~/.tmux/sessions/session1'
alias cls='clear'
alias fucking='sudo'
alias xclip="xclip -selection clipboard"
alias sudo='sudo '
alias yolo='git commit -m "minor change" && git push origin master'
alias please='sudo $(history -p !!)'
alias :q="exit"
alias :wq="exit"

# Aliases->Edit_Configs
alias zshconfig="nvim '$HOME'/.zshrc"
alias vimconfig="nvim '$HOME'/.config/nvim/init.vim" 
alias tmuxconfig="nvim '$HOME'/.tmux.conf"
alias hpsserve="cd '$HOME'/Codes/HelpPromptOffice/ && ionic serve --local --no-open"

# Aliases->Dirs
alias hps="cd /srv/http/"
alias codes="cd '$HOME'/Codes/"
alias etec="cd '$HOME'/Codes/ETEC/"
alias dotfiles="cd '$HOME'/Codes/dotfiles/"
alias hpo="cd '$HOME'/Codes/HelpPromptOffice/"

# Disables CTRL+S and CTRL+Q on the terminal
stty -ixon

